import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ConfigureAmplifyClientSide from '@/app/components/configureAmplify'
import '@aws-amplify/ui-react/styles.css'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ConfigureAmplifyClientSide />
				<div className="flex flex-col min-h-screen">
					<div className="flex-grow">{children}</div>
					<Footer />
				</div>
			</body>
		</html>
	)
}
